title: "colorify documentation"
description: "pkgdown site for the colorify R package"
theme: jekyll-theme-primer

# VERY IMPORTANT:
# Don't process or try to rebuild pkgdown's generated files.
# We just want to ship them as static.
exclude:
  - reference/
  - articles/
  - pkgdown.css
  - pkgdown.js
  - bootstrap.css
  - bootstrap.min.css
  - *.js
  - *.png
  - *.svg
  - *.ico
  - *.gif
  - *.jpg
  - *.jpeg
  - *.map
  - site_libs/
  - assets/css/style.scss

# turn off future-dated posts behavior
future: true